### ISSUE TITLE
Notifications issues

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#183]
- [x] Test all the actions and see if the notifications are thrown properly.
- [x] See pictures.
- [x] Inform about table reload and out-of-sync selected items, if there are selected items.
- [x] Action name: Not "{{ op }}", use "{{ action.name }}".
- [x] Smooth slide-up/down.
- [x] Remove bottom buttons.
- [x] Notification icons:
  - [x] Icon (best approach loader) for pending.
  - [x] Green tick for success.
  - [x] Red "X" for failure.

**Comment by athinab** [comment]
The related functionality has been updated.
Pending: Testing and style update.

**Comment by olgabrani** [comment]
Two more suggestions:
- [x] If notification are is empty, show a relevant message instead of an empty area
- [x] The message that appears after an action is `Click "Reload Table" to update them`. 
  However, there is no "Reload Table" button. Maybe it should be replaced with the reload icon?

Or, even better, add a  reload icon in the notification area?@AthinaB

**Comment by apyrgio** [comment]
I think that yesterday's testing has proved that notifications work properly. The only thing missing is the reload button and we can close this ticket.

**Comment by apyrgio** [comment]
The reload button has been added and the actions have been tested extensively. Only the issue with the empty area is left and this issue can close.
