### ISSUE TITLE
[~okeanos installation] Uitilization charts

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#313]
It seems that the percentage of used resources is very often between 0%-1%.
For example see the chart of infra usage.

Is this correct?

**Comment by apyrgio** [comment]
If you move the mouse over the chart, you will see the usage of each resource. This however is not depicted well in the chart because the free resources are set to sky-high numbers. E.g. when 10 TB are used from 954PB, the percentage will be 0%.

We can propose to the soc team to fix the resource limits. However, since this is not a bug, this issue will close.
