### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#44]
In the tables the dates should appear in 24-hour format.

**Comment by apyrgio** [comment]
Using our new approach (sending a JSON), the date format that the table shows is like the following: `2014-05-12T14:00:16.223`.

The above is in Greenwich time, in 24h format and is sortable. However, it is not very easy to the eyes because of the **'T'** between the date and time. Here's what's interesting however: the string representation of the above in python is actually `"2014-05-12 14:00:16.223"`. The problem is that we don't send the string representation of the date in our JSON, but a `datetime.datetime` Python instance, whose string representation in Javascript is `"2014-05-12T14:00:16.223"`.

The solution I've implemented is to define a format function in **django-eztables** that will allow us to format the `aaData` dictionary in any way we see fit. However, since this approach might be very slow (especially if we work in client-side mode), I'd suggest we take a look in Javascript, if there is a way to represent the `datetime.datetime` instance in a more human friendly way.

Athina, you can close this issue once you have an answer to the above.

**Comment by athinab** [comment]
Hi Alex,

The JSON I receive has a string representation of the date with "T" in it, so I guess you'd better change it in server-side.
